-- Insert images from the untitled folder to istanbul_rum archive
-- Generated by script

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '3f365463-241b-489f-91be-d8c3cd4565ab'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/buyukada-rum-yetimhanesi-1.webp',
    'istanbul_rum',
    'Büyükada Rum Yetimhanesi Öğrencileri',
    'Students of Büyükada Greek Orphanage',
    'Μαθητές του Ορφανοτροφείου Πριγκήπου',
    'Büyükada Rum Yetimhanesi Öğrencileri - Tarihî Fotoğraf',
    'Büyükada Rum Yetimhanesi Öğrencileri - Tarihî Fotoğraf',
    'Büyükada Rum Yetimhanesi Öğrencileri - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '4b55a5af-04c7-4121-b938-0966efc2cb1d'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/gokceada-rum-okulu-1.webp',
    'istanbul_rum',
    'Gökçeada (İmroz) Rum Okulu',
    'Gökçeada (Imbros) Greek School',
    'Ελληνικά Εκπαιδευτήρια Ίμβρου',
    'Gökçeada (İmroz) Rum Okulu - Tarihî Fotoğraf',
    'Gökçeada (İmroz) Rum Okulu - Tarihî Fotoğraf',
    'Gökçeada (İmroz) Rum Okulu - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '41354424-9f7f-4b55-a381-6c3007e06e64'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/gokceada-rum-okulu-1937.webp',
    'istanbul_rum',
    'Gökçeada Rum Okulu - 1937-1938 Eğitim Yılı',
    'Gökçeada Greek School - 1937-1938 Academic Year',
    'Ελληνικά Εκπαιδευτήρια Ίμβρου 1937-1938',
    'Gökçeada Rum Okulu - 1937-1938 Eğitim Yılı - Tarihî Fotoğraf 1937-1938',
    'Gökçeada Rum Okulu - 1937-1938 Eğitim Yılı - Tarihî Fotoğraf 1937-1938',
    'Gökçeada Rum Okulu - 1937-1938 Eğitim Yılı - Tarihî Fotoğraf 1937-1938',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    'ac33177f-ba10-49d0-9229-0149c2aa4f0c'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/zografyon-rum-ilkogretim-okulu-2-sinif-1907.webp',
    'istanbul_rum',
    'Özel Zoğrafyon Rum İlköğretim Okulu 2. Sınıf',
    'Zografyon Greek Primary School 2nd Grade',
    'Εκπαιδευτήρια Ζωγράφειου 2η Τάξη',
    'Özel Zoğrafyon Rum İlköğretim Okulu 2. Sınıf - Tarihî Fotoğraf 1907-1908',
    'Özel Zoğrafyon Rum İlköğretim Okulu 2. Sınıf - Tarihî Fotoğraf 1907-1908',
    'Özel Zoğrafyon Rum İlköğretim Okulu 2. Sınıf - Tarihî Fotoğraf 1907-1908',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '99a79376-dcee-4b7d-9d3d-b24238f07a93'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/zografyon-rum-okulu-bandosu-1907.webp',
    'istanbul_rum',
    'Özel Zoğrafyon Rum İlköğretim ve Lisesi Bandosu',
    'Zografyon Greek High School Band',
    'Μπάντα Εκπαιδευτηρίων Ζωγράφειου',
    'Özel Zoğrafyon Rum İlköğretim ve Lisesi Bandosu - Tarihî Fotoğraf 1907-1908',
    'Özel Zoğrafyon Rum İlköğretim ve Lisesi Bandosu - Tarihî Fotoğraf 1907-1908',
    'Özel Zoğrafyon Rum İlköğretim ve Lisesi Bandosu - Tarihî Fotoğraf 1907-1908',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '0c30df83-e80f-41f4-b6f1-ea1da2003ad2'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/kadikoy-rum-okulu-1.webp',
    'istanbul_rum',
    'Kadıköy Rum Okulu',
    'Kadiköy Greek School',
    'Ελληνικό Σχολείο Χαλκηδόνας',
    'Kadıköy Rum Okulu - Tarihî Fotoğraf',
    'Kadıköy Rum Okulu - Tarihî Fotoğraf',
    'Kadıköy Rum Okulu - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '103dda3a-336d-4978-8e56-274fe6d916bd'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/beyoglu-kiz-lisesi-ogrencileri.webp',
    'istanbul_rum',
    'Beyoğlu Foto Palas Özel Kız Lisesi Öğrencileri',
    'Students of Beyoğlu Private Girls'' High School',
    'Μαθήτριες Ιδιωτικού Παρθεναγωγείου Πέραν',
    'Beyoğlu Foto Palas Özel Kız Lisesi Öğrencileri - Tarihî Fotoğraf',
    'Beyoğlu Foto Palas Özel Kız Lisesi Öğrencileri - Tarihî Fotoğraf',
    'Beyoğlu Foto Palas Özel Kız Lisesi Öğrencileri - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '80c58b83-99a1-4f7c-ade2-10a554cf1cb2'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/istanbul-rum-okullari-ogrenci-grubu-1.webp',
    'istanbul_rum',
    'İstanbul Rum Okulları - Öğrenci Grubu',
    'Istanbul Greek Schools - Student Group',
    'Ρωμαίικα Σχολεία της Πόλης - Ομάδα Μαθητών',
    'İstanbul Rum Okulları - Öğrenci Grubu - Tarihî Fotoğraf',
    'İstanbul Rum Okulları - Öğrenci Grubu - Tarihî Fotoğraf',
    'İstanbul Rum Okulları - Öğrenci Grubu - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '67cbfbc0-f5a3-4ad4-935a-a55a83c76134'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/yesilkoy-rum-karma-ilkokulu-1.webp',
    'istanbul_rum',
    'Yeşilköy Rum Karma İlk Okulu',
    'Yeşilköy Greek Mixed Primary School',
    'Ελληνικό Μικτό Σχολείο Αγίου Στεφάνου',
    'Yeşilköy Rum Karma İlk Okulu - Tarihî Fotoğraf',
    'Yeşilköy Rum Karma İlk Okulu - Tarihî Fotoğraf',
    'Yeşilköy Rum Karma İlk Okulu - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    'e4a0203f-ea7c-4b3c-84fc-9a7a985dda82'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/buyukdere-rum-okulu-etkinlik.webp',
    'istanbul_rum',
    'Büyükdere Rum Okulu Topluluk Etkinliği',
    'Büyükdere Greek School Community Event',
    'Εκδήλωση Ελληνικού Σχολείου Βαθυρύακος',
    'Büyükdere Rum Okulu Topluluk Etkinliği - Tarihî Fotoğraf',
    'Büyükdere Rum Okulu Topluluk Etkinliği - Tarihî Fotoğraf',
    'Büyükdere Rum Okulu Topluluk Etkinliği - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '74bbf628-2015-4f63-a6b8-8778b0edfbdc'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/gokceada-rum-okulu-1954-1955.webp',
    'istanbul_rum',
    'Gökçeada Rum Okulu - 1954-1955 Eğitim Yılı',
    'Gökçeada Greek School - 1954-1955 Academic Year',
    'Ελληνικά Εκπαιδευτήρια Ίμβρου 1954-1955',
    'Gökçeada Rum Okulu - 1954-1955 Eğitim Yılı - Tarihî Fotoğraf 1954-1955',
    'Gökçeada Rum Okulu - 1954-1955 Eğitim Yılı - Tarihî Fotoğraf 1954-1955',
    'Gökçeada Rum Okulu - 1954-1955 Eğitim Yılı - Tarihî Fotoğraf 1954-1955',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    'fb0f5d9b-2650-4161-95bc-6c0f72b4b29b'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/arnavutkoy-mega-revma-rum-okulu-1.webp',
    'istanbul_rum',
    'Arnavutköy (Mega Revma) Rum Okulu',
    'Arnavutköy (Mega Revma) Greek School',
    'Ελληνικό Σχολείο Μέγα Ρεύματος',
    'Arnavutköy (Mega Revma) Rum Okulu - Tarihî Fotoğraf',
    'Arnavutköy (Mega Revma) Rum Okulu - Tarihî Fotoğraf',
    'Arnavutköy (Mega Revma) Rum Okulu - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '17186c51-9dbb-412e-b2ee-754d9be07d97'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/arnavutkoy-mega-revma-rum-okulu-2.webp',
    'istanbul_rum',
    'Arnavutköy (Mega Revma) Rum Okulu Öğrencileri',
    'Students of Arnavutköy (Mega Revma) Greek School',
    'Μαθητές Ελληνικού Σχολείου Μέγα Ρεύματος',
    'Arnavutköy (Mega Revma) Rum Okulu Öğrencileri - Tarihî Fotoğraf 1959',
    'Arnavutköy (Mega Revma) Rum Okulu Öğrencileri - Tarihî Fotoğraf 1959',
    'Arnavutköy (Mega Revma) Rum Okulu Öğrencileri - Tarihî Fotoğraf 1959',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    'be711c4b-88c9-44b7-9525-8d39a41c16cb'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/arnavutkoy-mega-revma-rum-okulu-3.webp',
    'istanbul_rum',
    'Arnavutköy (Mega Revma) Rum Okulu Topluluğu',
    'Arnavutköy (Mega Revma) Greek School Community',
    'Κοινότητα Ελληνικού Σχολείου Μέγα Ρεύματος',
    'Arnavutköy (Mega Revma) Rum Okulu Topluluğu - Tarihî Fotoğraf',
    'Arnavutköy (Mega Revma) Rum Okulu Topluluğu - Tarihî Fotoğraf',
    'Arnavutköy (Mega Revma) Rum Okulu Topluluğu - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '04fefa0c-1bb1-48b0-bc04-9d33b48acde5'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/uskudar-rum-okulu-1956.webp',
    'istanbul_rum',
    'Üsküdar (Skoutari) Rum Okulu',
    'Üsküdar (Skoutari) Greek School',
    'Ελληνικό Σχολείο Σκουταρίου',
    'Üsküdar (Skoutari) Rum Okulu - Tarihî Fotoğraf 1956',
    'Üsküdar (Skoutari) Rum Okulu - Tarihî Fotoğraf 1956',
    'Üsküdar (Skoutari) Rum Okulu - Tarihî Fotoğraf 1956',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    'bc0c85f9-20ef-4e7e-9821-0c81936e94d2'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/istanbul-rum-okullari-topluluk-etkinligi.webp',
    'istanbul_rum',
    'İstanbul Rum Okulları - Topluluk Etkinliği',
    'Istanbul Greek Schools - Community Event',
    'Κοινοτική Εκδήλωση',
    'İstanbul Rum Okulları - Topluluk Etkinliği - Tarihî Fotoğraf',
    'İstanbul Rum Okulları - Topluluk Etkinliği - Tarihî Fotoğraf',
    'İstanbul Rum Okulları - Topluluk Etkinliği - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '5d872827-d507-4713-879a-70f7163de281'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/kurtulus-rum-okulu-5-sinif.webp',
    'istanbul_rum',
    'Kurtuluş Rum Okulu 5. Sınıf',
    'Kurtuluş Greek School 5th Grade',
    '5η Τάξη Ελληνικού Σχολείου Ταταούλων',
    'Kurtuluş Rum Okulu 5. Sınıf - Tarihî Fotoğraf',
    'Kurtuluş Rum Okulu 5. Sınıf - Tarihî Fotoğraf',
    'Kurtuluş Rum Okulu 5. Sınıf - Tarihî Fotoğraf',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '40641877-4c03-4ee1-996d-f5ecb8b82552'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/kurtulus-rum-okulu-1970-1.webp',
    'istanbul_rum',
    'Kurtuluş Rum Okulu Öğrencileri',
    'Students of Kurtuluş Greek School',
    'Μαθητές Ελληνικού Σχολείου Ταταούλων',
    'Kurtuluş Rum Okulu Öğrencileri - Tarihî Fotoğraf 1970',
    'Kurtuluş Rum Okulu Öğrencileri - Tarihî Fotoğraf 1970',
    'Kurtuluş Rum Okulu Öğrencileri - Tarihî Fotoğraf 1970',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    'a4324248-996d-42f2-bc2b-7ce3291f552f'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/kurtulus-rum-okulu-1970-ogretmenler.webp',
    'istanbul_rum',
    'Kurtuluş Rum Okulu Öğretmenleri',
    'Teachers of Kurtuluş Greek School',
    'Δάσκαλοι Ελληνικού Σχολείου Ταταούλων',
    'Kurtuluş Rum Okulu Öğretmenleri - Tarihî Fotoğraf 1970',
    'Kurtuluş Rum Okulu Öğretmenleri - Tarihî Fotoğraf 1970',
    'Kurtuluş Rum Okulu Öğretmenleri - Tarihî Fotoğraf 1970',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '97864dbf-d24e-44d7-91de-0e66fcc4b022'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/kurtulus-rum-okulu-1970-sinif.webp',
    'istanbul_rum',
    'Kurtuluş Rum Okulu Sınıf Fotoğrafı',
    'Kurtuluş Greek School Class Photo',
    'Φωτογραφία Τάξης Ελληνικού Σχολείου Ταταούλων',
    'Kurtuluş Rum Okulu Sınıf Fotoğrafı - Tarihî Fotoğraf 1970',
    'Kurtuluş Rum Okulu Sınıf Fotoğrafı - Tarihî Fotoğraf 1970',
    'Kurtuluş Rum Okulu Sınıf Fotoğrafı - Tarihî Fotoğraf 1970',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.artifacts (
    id, category_id, sub_category_id, image_url, archive_type,
    title_tr, title_en, title_el,
    description_tr, description_en, description_el,
    provenance_tr, provenance_en, provenance_el,
    status
) VALUES (
    '063e05ef-34b1-4afd-9aa5-a39ad5daeffe'::uuid,
    'a1000000-0000-0000-0000-000000000002'::uuid,
    'b1000000-0000-0000-0000-000000000003'::uuid,
    '/images/artifacts/ogretmenler-afroditi-gogou-anna-melakopoulou.webp',
    'istanbul_rum',
    'Kadın Öğretmenler',
    'Female Teachers',
    'Γυναίκες Δασκάλες',
    'Kadın Öğretmenler - Tarihî Fotoğraf 1958-1959',
    'Kadın Öğretmenler - Tarihî Fotoğraf 1958-1959',
    'Kadın Öğretmenler - Tarihî Fotoğraf 1958-1959',
    'İstanbul Rum Okulları Arşivi',
    'Istanbul Greek Schools Archive',
    'Αρχείο Ρωμαίικων Σχολείων Κωνσταντινούπολης',
    'published'
) ON CONFLICT (id) DO NOTHING;

